services:
  app_db:
    image: postgres:18
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9090:9000"
      - "9091:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
volumes:
  app_db_data:
  minio_data:
