package org.vitalii.fedyk.minio.usecase;

import java.util.UUID;
import org.vitalii.fedyk.minio.model.ChunkUploadRequest;
import org.vitalii.fedyk.minio.model.CompleteRequest;
import org.vitalii.fedyk.minio.model.FileUpload;
import org.vitalii.fedyk.minio.model.InitiateUploadResponse;
import org.vitalii.fedyk.minio.model.StorageInfo;

/** A use case interface for handling file storage operations. */
public interface FileManagementService {

  /**
   * Saves a file associated with the specified application name.
   *
   * @param appName the name of the application the file belongs to
   * @param fileUpload the request object
   * @return a {@link StorageInfo} object containing information about the stored file
   */
  StorageInfo save(String appName, FileUpload fileUpload);

  /**
   * Retrieves information about a stored file by its unique identifier.
   *
   * @param id the unique identifier of the stored file
   * @return a {@link StorageInfo} object containing information about the file, or {@code null} if
   *     no file with the given ID exists
   */
  StorageInfo findById(UUID id);

  /**
   * Initiates a multipart upload session for large files. This is the first step in the upload
   * flow. It registers the intent to upload with MinIO and returns a unique Upload ID. This ID must
   * be used in all subsequent 'uploadChunk' and 'complete' calls.
   *
   * @param fileName The original name of the file (e.g., "video_5gb.mp4").
   * @param appName The application identifier, used to determine the target MinIO bucket.
   * @return A unique String {@code uploadId} generated by MinIO to track this session.
   */
  InitiateUploadResponse initiateUpload(String fileName, String appName);

  /**
   * Processes the upload of an individual file chunk for a specific application.
   *
   * @param appName the identifier of the application.
   * @param chunkUploadRequest the domain model containing the chunk's binary data, sequence index,
   *     and original file metadata
   * @return a unique identifier (such as an ETag ) confirming successful storage.
   */
  String uploadChunk(String appName, ChunkUploadRequest chunkUploadRequest);

  /**
   * Finalizes the multipart upload process by reassembling all uploaded chunks. This method sends a
   * request to the storage backend (S3/MinIO) to verify the provided ETags and merge the parts in
   * the specified order. Once this call succeeds, the individual chunks are deleted, and the final
   * object becomes available for retrieval via its Key.
   *
   * @param appName the identifier of the application.
   * @param completeRequest A DTO containing the {@code uploadId}, the target {@code fileName}
   *     (Key), and the ordered list of {@code PartEtag} receipts.
   * @return access url
   */
  StorageInfo completeUpload(String appName, CompleteRequest completeRequest);
}
