openapi: 3.0.2
info:
  title: Bibliotopia Storage API
  version: 1.0.0
  description: API for uploading files to different storages
  contact:
    name: Vitalii Fedyk
    email: fedykvitalik2004@gmail.com
paths:
  /storage/upload:
    post:
      summary: Upload a file to a specified storage backend
      operationId: uploadFile
      tags:
        - Storage
      requestBody:
        $ref: '#/components/requestBodies/UploadFileDto'
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: File saved successfully
                  location:
                    type: string
                    description: Location or URL where the file is stored
                    example: storage-files/myfile.txt

components:
  requestBodies:
    UploadFileDto:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            required:
              - file
              - storageType
            properties:
              file:
                type: string
                format: binary
                description: The file to upload
              storageType:
                type: string
                description: Storage backend to use
                enum:
                  - filesystem
                  - s3
              duration:
                type: string
                description: Duration to keep the file in the format of ISO 8601 duration
                example: PT24H







