name: SonarCloud Analysis
on:
  push:
    branches:
     - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  sonarcloud:
    name: Sonarcloud analysis
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v2.1.0
        with:
          projectKey: fedykvitalik2004_bibliotopia-storage
          organization: bibliotopia
          token: ${{ secrets.SONAR_TOKEN }}
          args: mvn clean verify sonar:sonar -DskipTests
    
